# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfstate-apache-prod-eu-central-1"
    dynamodb_table = "tfstate-lock-table-prod-apache"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "default"
    region         = "eu-central-1"
  }
}
