Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.define "client" do |client|
    client.vm.provider "virtualbox" do |vb|
      config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
      vb.gui = true
      vb.cpus = "1"
      vb.memory = "1024"
    end
  end
  config.vm.define "web" do |web|    
    web.vm.provider "virtualbox" do |vb|
      config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
      vb.gui = true
      vb.cpus = "2"
      vb.memory = "2048"
    end
    web.vm.provision "shell", inline: <<-SHELL
         apt-get install nginx -y
         systemctl start nginx && systemctl enable nginx
    SHELL
  end
end
